server:
  port: 8081
#  servlet:
#    context-path: /xxxx
  #jetty配置，主要是acceptors和selectors
  jetty:
    acceptors: 2
    selectors: 4
  #tomcat的配置可以保留，切换回来可用，反正不会生效
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 2000
    #background-processor-delay: 30
    max-http-header-size: 8096
#    basedir: ${user.home}/tomcat/tmp
    max-connections: 5000
    max-http-form-post-size: 10000000
    connection-timeout: 600000
  # 下面是配置undertow作为服务器的参数
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

spring:
  main:
    web-application-type: reactive
  data:
    ## Redis 配置
    redis:
      ## Redis服务器地址
      host: 127.0.0.1
      ## Redis服务器连接端口
      port: 6379
      ## Redis服务器连接密码（默认为空）
      password:
      # 连接超时时间（毫秒）,这里注意的是连接超时时间不能太少或者为 0，不然会引起异常 RedisCommandTimeoutException: Command timed out
      timeout: 5000
    #mongodb的配置
#    mongodb:
#      database: admin
#      host: 192.168.0.104
#      port: 27017
#      username: admin
#      password: admin
#      uri: mongodb://localhost:27017/webflux_demo


#spring.data.redis.repositories.enabled=true
#spring.main.banner-mode=off
#server.address=127.0.0.1

