server:
  port: 8081
  application:
    name: first
#  servlet:
#    context-path: /xxxx
  #jetty配置，主要是acceptors和selectors
  jetty:
    acceptors: 2
    selectors: 4
  #tomcat的配置可以保留，切换回来可用，反正不会生效
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 2000
    #background-processor-delay: 30
    max-http-header-size: 8096
#    basedir: ${user.home}/tomcat/tmp
    max-connections: 5000
    max-http-form-post-size: 10000000
    connection-timeout: 600000
  # 下面是配置undertow作为服务器的参数
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

